# Generated by Django 2.1.2 on 2018-10-23 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Model1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('var1', models.CharField(max_length=10)),
                ('var2', models.CharField(max_length=50)),
                ('var3', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Model2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whole_var', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='aplication.Model1')),
            ],
        ),
        migrations.CreateModel(
            name='Model3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other_var', models.CharField(max_length=1)),
                ('second_var', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='aplication.Model2')),
            ],
        ),
    ]
